services:

  db:
    image: postgres:15
    container_name: postgres_nyc

    environment:
      POSTGRES_USER: user_spark
      POSTGRES_PASSWORD: password_spark
      POSTGRES_DB: nyc_taxi

    ports:
      - "5432:5432"

    networks:
      - taxi_network

  spark-master:
    build: .
    user: "0:0"
    container_name: spark-master

    environment:
      - SPARK_MODE=master

    ports:
      - "8080:8080"
      - "7077:7077"

    volumes:
      - ../:/jobs

    networks:
      - taxi_network

    entrypoint: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master" ]

  spark-worker:
    build: .
    user: "0:0"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G

    volumes:
      - ../:/jobs

    networks:
      - taxi_network

    depends_on:
      - spark-master

    entrypoint: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077" ]

networks:
  taxi_network:
    driver: bridge